spring:
  application:
    name: life-line-back-end
  datasource:
    url: jdbc:postgresql://localhost:5432/lifelinedb
    username: aki
    password: aki
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

    # with the lines above, we already create the tables and load the data defalt "data.sql", the below instruction
    # we only use it if we want specifically for postgress to use schema-postgresql.sql #data-postgresql.sql instead of data.sql
#  sql:
#    init:
#      platform: postgresql
#      mode: always
