INSERT INTO DAY (read_only, score, date, description)
VALUES (true, 7, '2025/02/12',
        'Today was a challenging day, but I managed to complete my tasks successfully. I felt motivated and productive throughout the afternoon. Despite some difficulties, I kept a positive mindset and pushed through. Overall, it was a day of growth and progress.'),
       (true, 4, '2025/02/13',
        'The day started off slow and a bit frustrating. However, I found small moments to enjoy and relax. I need to work on staying focused during busy times. Tomorrow will be better and I am hopeful.'),
       (true, 9, '2025/02/14',
        'I accomplished a lot today and felt very energetic. The morning went smoothly and I tackled some complex problems. I am proud of my dedication and effort. This day will be remembered as productive and rewarding.'),
       (true, 3, '2025/02/15',
        'Today was tough and stressful. I struggled to keep up with my schedule. There were many distractions that slowed me down. I hope to improve my time management moving forward.'),
       (true, 6, '2025/02/16',
        'I had a fairly good day with some ups and downs. I managed to balance work and rest fairly well. I learned new things that might help me soon. Feeling optimistic about what’s coming next.'),
       (true, 5, '2025/02/17',
        'The day was average, nothing extraordinary happened. I completed the basic tasks but lacked motivation. I need to find ways to stay more engaged. Hopefully, tomorrow will bring more inspiration.'),
       (true, 8, '2025/02/18',
        'I had a productive and fulfilling day. I managed to complete several important assignments. I felt focused and motivated throughout. Looking forward to maintaining this momentum.'),
       (true, 2, '2025/02/19',
        'Today was quite difficult and exhausting. I faced unexpected challenges and felt overwhelmed. I need to rest and recharge to come back stronger. Tomorrow is a new opportunity.'),
       (true, 10, '2025/02/20',
        'This was an excellent day filled with success. I achieved all my goals and felt extremely satisfied. The positive energy was contagious and motivating. I hope to keep this streak going.'),
       (true, 1, '2025/02/21',
        'It was a very bad day with many setbacks. I struggled with concentration and motivation. Everything seemed to go wrong and I felt discouraged. I need to learn from this and move forward.'),
       (true, 6, '2025/02/22',
        'The day had its challenges but I managed well. I stayed calm and focused despite the pressure. I made progress on some difficult tasks. Feeling more confident about my skills.'),
       (true, 4, '2025/02/23',
        'Today was somewhat disappointing. I did not achieve as much as I hoped. I found myself distracted and tired. I will try to improve my focus tomorrow.'),
       (true, 7, '2025/02/24',
        'I had a fairly good day with a few highlights. I completed most of my to-dos and felt accomplished. I am learning to manage stress better. Overall, it was a positive experience.'),
       (true, 3, '2025/02/25',
        'The day was rough and I felt unmotivated. I struggled to keep up with the workload. I hope to find better strategies to cope with pressure. Tomorrow is a fresh start.'),
       (true, 8, '2025/02/26',
        'I felt productive and energetic today. I finished tasks ahead of schedule and felt proud. It was satisfying to see progress in my work. Looking forward to continuing this trend.'),
       (true, 5, '2025/02/27',
        'An average day with some moments of distraction. I completed most tasks but felt tired. Need to work on maintaining energy throughout the day. Hoping for more focus tomorrow.'),
       (true, 9, '2025/02/28',
        'A very productive day with great results. I was able to overcome challenges efficiently. Felt motivated and determined throughout. This kind of day boosts my confidence.'),
       (true, 2, '2025/03/01',
        'Today was exhausting and stressful. I struggled with several problems and felt drained. I need to prioritize rest and self-care. Tomorrow should be better.'),
       (true, 10, '2025/03/02',
        'An excellent day filled with achievements. I met all my goals and felt proud. Positive energy carried me through the day. I want to keep this momentum going.'),
       (true, 1, '2025/03/03',
        'It was a very difficult day with many setbacks. I lacked focus and motivation. Everything seemed to fall apart and I felt discouraged. I must learn from this experience.'),
       (true, 6, '2025/03/04',
        'The day went okay with some positive moments. I managed to complete important tasks. I am hopeful for improvement in the coming days. Staying positive despite challenges.'),
       (true, 4, '2025/03/05',
        'Today was a bit disappointing. I struggled to keep up with the pace. I felt distracted and unfocused. Need to find better ways to maintain attention.'),
       (true, 7, '2025/03/06',
        'A fairly good day with some accomplishments. I felt motivated and productive. Managed to solve problems effectively. Looking forward to more days like this.'),
       (true, 3, '2025/03/07',
        'The day was tough and challenging. I faced many obstacles and felt drained. I need to improve my time management. Tomorrow is a new opportunity to try again.'),
       (true, 8, '2025/03/08',
        'I had a productive day with good results. I stayed focused and completed all tasks. Felt confident and energized throughout. Hoping to maintain this streak.'),
       (true, 5, '2025/03/09',
        'An average day with some distractions. I finished most work but felt tired. Need to work on sustaining energy levels. Tomorrow is a fresh start.'),
       (true, 9, '2025/03/10',
        'A very productive day filled with success. I achieved important milestones. Felt motivated and determined. Days like this keep me moving forward.'),
       (true, 2, '2025/03/11',
        'Today was stressful and tiring. I faced difficulties and felt overwhelmed. Need to focus on rest and recovery. Tomorrow should bring better results.'),
       (true, 10, '2025/03/12',
        'An excellent day with lots of achievements. I met all goals and felt proud. Positive energy kept me going strong. I want to keep this momentum alive.'),
       (true, 1, '2025/03/13',
        'It was a tough day with many challenges. I struggled to stay focused and motivated. Felt discouraged by setbacks. I need to learn and grow from this.'),
       (true, 6, '2025/03/14',
        'The day was okay with some positive points. I completed tasks and stayed calm. Hopeful for better days ahead. Staying optimistic despite difficulties.'),
       (true, 4, '2025/03/15',
        'Today was somewhat disappointing. I struggled to maintain focus. Felt distracted and tired. Need to improve my concentration skills.'),
       (true, 7, '2025/03/16',
        'A fairly good day with accomplishments. I felt motivated and productive. Managed to solve problems efficiently. Looking forward to more success.'),
       (true, 3, '2025/03/17',
        'The day was hard and tiring. Faced many obstacles and challenges. Need to work on time management. Tomorrow is a chance to improve.'),
       (true, 8, '2025/03/18',
        'I had a productive and energizing day. I stayed focused and completed tasks on time. Felt confident and satisfied. Hoping to maintain this momentum.'),
       (true, 5, '2025/03/19',
        'An average day with some distractions. I completed most tasks but felt tired. Need to maintain energy better. Tomorrow is a new opportunity.'),
       (true, 9, '2025/03/20',
        'A highly productive day with great results. Achieved important goals successfully. Felt motivated and determined. Days like these are very encouraging.'),
       (true, 2, '2025/03/21',
        'Today was challenging and stressful. Faced difficulties and felt overwhelmed. Need to rest and recharge. Tomorrow will be better.'),
       (true, 10, '2025/03/22',
        'An excellent day full of achievements. Met all goals and felt proud. Positive energy carried me through. Want to keep this momentum.'),
       (true, 1, '2025/03/23',
        'It was a very difficult day with setbacks. Struggled with motivation and focus. Felt discouraged by failures. Need to learn and improve.'),
       (true, 6, '2025/03/24',
        'The day went okay with some good moments. Completed tasks and stayed calm. Hopeful for better days. Staying positive.'),
       (true, 4, '2025/03/25',
        'Today was a bit disappointing. Struggled with focus and energy. Felt tired and distracted. Need to find better strategies.'),
       (true, 7, '2025/03/26',
        'A fairly good day with some progress. Felt motivated and productive. Solved problems effectively. Looking forward to more success.'),
       (true, 3, '2025/03/27',
        'The day was tough and exhausting. Faced many challenges. Need to improve time management. Tomorrow is a new chance.'),
       (true, 8, '2025/03/28',
        'Had a productive and focused day. Completed tasks on time. Felt confident and energized. Hope to keep this streak.'),
       (true, 5, '2025/03/29',
        'An average day with distractions. Finished most work but felt tired. Need to sustain energy better. Tomorrow is fresh start.'),
       (true, 9, '2025/03/30',
        'Very productive day with achievements. Reached important goals. Felt motivated and determined. Days like these inspire me.'),
       (true, 2, '2025/03/31',
        'Challenging and stressful day. Faced difficulties and felt overwhelmed. Need to rest and recharge. Tomorrow will improve.'),
       (true, 10, '2025/04/01',
        'Excellent day full of success. Met all goals and felt proud. Positive energy kept me going strong. Want to keep momentum.');
